---
- name: ethminer configuration
  hosts: "{{ miner | default('miners') }}"
  gather_facts: false

  tasks:
    - name: get uptime
      command: uptime
      register: uptime
    - name: get disk
      shell: df -h
      register: disk
    - name: get memory
      shell: head -3 /proc/meminfo 
      register: memory
    - name: get proc
      shell: ps -efww | grep ethminer
      register: running_proc
    - name: get power
      shell: nvidia-smi -q -d POWER
      register: power
 
    - name: print uptime
      debug:
        var: uptime.stdout
    - name: print disk
      debug:
        var: disk.stdout_lines
    - name: print memory
      debug:
        var: memory.stdout_lines
    - name: print proc
      debug:
        var: running_proc.stdout
    - name: power
      debug:
        var: power.stdout_lines
