---
- name: ethminer configuration
  hosts: "{{ miner | default('miners') }}"
  gather_facts: false

  tasks:
    - name: get ethminer version
      command: ethminer --version
      register: ethminer_version
    - name: get system_build
      command: uname -a
      register: system_build
    #- name: get grub boot
    #  command: grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub
    #  register: grub_boot
    - name: get cpu procs
      command: grep name /proc/cpuinfo
      register: cpu_procs


<<<<<<< HEAD
    - name: print ethminer version
      debug:
        var: ethminer_version.stderr
=======
>>>>>>> 90159b48586348d78f3a2fb474b09c7da8ae3db5
    - name: print system build
      debug:
        var: system_build.stdout
    #- name: print grub boot
    #  debug:
    #    var: grub_boot.stdout_lines
    - name: print cpu procs
      debug:
        var: cpu_procs.stdout_lines
    - name: print ethminer version
      debug:
        var: ethminer_version.stderr
