---
- name: install cuda
  hosts: "{{ miner | default('miners') }}"
  gather_facts: false


  tasks:
    - name: get cuda
      get_url:
        url: https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.39_linux.run
        dest: "{{ lookup('env', 'HOME') }}/cuda_10.1.105_418.39_linux.run"
        mode: 0755
      register: cuda_download

    - debug:
        var: cuda_download

    - name: install cuda 
      become: yes
      command: "{{ lookup('env', 'HOME') }}/cuda_10.1.105_418.39_linux.run --silent --driver --toolkit"
      register: cuda_install

    - debug:
        var: cuda_install
