---
- name: ethminer configuration
  hosts: "{{ miner | default('miners') }}"
  gather_facts: true
  serial: 1

  # v0.13.0
  # v0.14.0
  # v0.15.0rc2

  roles:
  - { role: ethminer, ethminer_release: "{{ version | default('v0.14.0') }}" }
