---
- name: ethminer update systemd
  hosts: "{{ miner | default('miners') }}"
  gather_facts: true

 
  tasks:
    - name: set miner vars
      set_fact:
        wallet: "{{ lookup('env', 'ETHER_WALLET') }}"
        email: "{{ lookup('env', 'ETHER_MINE_EMAIL') }}"

    - name: print wallet
      debug:
        var: wallet

    - name: print email
      debug:
        var: email

    - name: exit if unset vars
      fail:
        msg: miner wallet and email must be exported to environment
      when: (wallet | length == 0) or (email | length == 0)

    - name: install systemd init script - v4 - ethermine
      template:
        src: mine.service.v4.j2
        dest: /etc/systemd/system/mine.service
      notify:
        - reload systemd
        - restart mine
      become: yes

  handlers:
    - name: reload systemd
      become: yes
      command: systemctl daemon-reload

    - name: restart mine
      become: yes
      command: systemctl restart mine
