---
- name: restart ethminer
  hosts: "{{ miner | default('miners') }}"
  gather_facts: false

  tasks:
    - name: restart miner
      service:
        name: mine
        state: restarted
      register: restart
      become: yes

    - name: print restart miner
      debug:
        var: restart.stdout
